#!/usr/bin/env python3
"""Turn an exported ledger (scripts/sync_tracker.py export) into one SQL file.

    python scripts/sync_tracker.py export --out DIR
    python scripts/build_supabase_migration.py --in DIR --email you@example.com \
        --out tracker/supabase_seed.sql

The rows are attached to the signed-in user by looking the account up by email,
so the file never contains a user id, a password or a key - and it runs in the
Supabase SQL Editor, which executes as postgres and therefore does not need a
session at all.

Re-running it is safe: every insert upserts on (user_id, id).
"""
import argparse, json, os, sys

CORE = ["pokemon", "mega", "ability", "mega_ability", "nature",
        "stat_points", "moves", "role", "rationale"]


def q(v):
    """A SQL string literal, or NULL."""
    if v is None:
        return "NULL"
    return "'" + str(v).replace("'", "''") + "'"


def jq(v):
    """A jsonb literal."""
    return q(json.dumps(v if v is not None else {}, ensure_ascii=False)) + "::jsonb"


def aq(v):
    """A text[] literal."""
    items = [x for x in (v or []) if x]
    if not items:
        return "'{}'::text[]"
    return "array[" + ", ".join(q(x) for x in items) + "]::text[]"


def read(d, coll):
    p = os.path.join(d, coll)
    if not os.path.isdir(p):
        return {}
    return {f[:-5]: json.load(open(os.path.join(p, f), encoding="utf-8"))
            for f in sorted(os.listdir(p)) if f.endswith(".json")}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--in", dest="inp", required=True)
    ap.add_argument("--email", required=True)
    ap.add_argument("--out", required=True)
    a = ap.parse_args()

    box = read(a.inp, "box")
    builds = read(a.inp, "builds")
    meta = read(a.inp, "meta")
    if not (box or builds or meta):
        sys.exit("nothing to migrate under " + a.inp)

    L = []
    w = L.append
    w("-- Champions Ledger - initial data")
    w("-- Generated by scripts/build_supabase_migration.py. Safe to re-run.")
    w("--")
    w("-- Paste into the Supabase SQL Editor and press Run. It executes as")
    w("-- postgres, so it loads the rows without needing you to be signed in;")
    w("-- from then on RLS is what governs every read the app makes.")
    w("")
    w("do $migrate$")
    w("declare uid uuid;")
    w("begin")
    w("  select id into uid from auth.users where email = %s;" % q(a.email))
    w("  if uid is null then")
    w("    raise exception 'No account for %s - create the user first "
      "(Authentication -> Users -> Add user, with Auto Confirm ticked).';"
      % a.email.replace("'", "''"))
    w("  end if;")
    w("")

    # ------------------------------------------------------------- box ----
    if box:
        w("  -- %d Pokemon" % len(box))
        w("  insert into public.box "
          "(user_id, id, name, location, status, origin, note, ord) values")
        rows = []
        for i, (did, d) in enumerate(sorted(box.items())):
            rows.append("    (uid, %s, %s, %s, %s, %s, %s, %d)" % (
                q(did), q(d.get("name")), q(d.get("location") or "champions"),
                q(d.get("status") or "permanent"), q(d.get("origin") or "unknown"),
                q(d.get("note") or ""), int(d.get("order") or 0)))
        w(",\n".join(rows))
        w("  on conflict (user_id, id) do update set")
        w("    name = excluded.name, location = excluded.location,")
        w("    status = excluded.status, origin = excluded.origin,")
        w("    note = excluded.note, ord = excluded.ord;")
        w("")

    # ---------------------------------------------------------- builds ----
    if builds:
        w("  -- %d builds" % len(builds))
        w("  insert into public.builds (user_id, id, pokemon, mega, ability,")
        w("    mega_ability, nature, stat_points, moves, role, rationale, extra) values")
        rows = []
        for did, d in sorted(builds.items()):
            rows.append("    (uid, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)" % (
                q(did), q(d.get("pokemon")), q(d.get("mega")), q(d.get("ability")),
                q(d.get("mega_ability")), q(d.get("nature")),
                jq(d.get("stat_points")), aq(d.get("moves")),
                q(d.get("role") or ""), q(d.get("rationale") or ""),
                jq(d.get("extra"))))
        w(",\n".join(rows))
        w("  on conflict (user_id, id) do update set")
        w("    pokemon = excluded.pokemon, mega = excluded.mega,")
        w("    ability = excluded.ability, mega_ability = excluded.mega_ability,")
        w("    nature = excluded.nature, stat_points = excluded.stat_points,")
        w("    moves = excluded.moves, role = excluded.role,")
        w("    rationale = excluded.rationale, extra = excluded.extra;")
        w("")

    # ------------------------------------------------------------ meta ----
    if meta:
        w("  -- trainer, stones, items, gts")
        w("  insert into public.meta (user_id, id, data) values")
        rows = []
        for did, d in sorted(meta.items()):
            body = {k: v for k, v in d.items() if k != "updated"}
            rows.append("    (uid, %s, %s)" % (q(did), jq(body)))
        w(",\n".join(rows))
        w("  on conflict (user_id, id) do update set data = excluded.data;")
        w("")

    w("end")
    w("$migrate$;")
    w("")
    w("-- what landed")
    w("select 'box' as t, count(*) from public.box")
    w("union all select 'builds', count(*) from public.builds")
    w("union all select 'meta', count(*) from public.meta")
    w("union all select 'box: HOME origin', count(*) from public.box")
    w("  where location = 'champions' and status = 'permanent' and origin = 'home'")
    w("union all select 'box: Champions origin', count(*) from public.box")
    w("  where location = 'champions' and status = 'permanent' and origin = 'champions'")
    w("union all select 'box: origin unknown', count(*) from public.box")
    w("  where location = 'champions' and status = 'permanent' and origin = 'unknown'")
    w("union all select 'box: rental', count(*) from public.box")
    w("  where status = 'rental'")
    w("union all select 'in HOME', count(*) from public.box")
    w("  where location = 'home';")

    out = "\n".join(L) + "\n"
    os.makedirs(os.path.dirname(a.out) or ".", exist_ok=True)
    open(a.out, "w", encoding="utf-8").write(out)
    print("wrote %s  (%.0f KB)" % (a.out, len(out.encode()) / 1024))
    print("  %d box, %d builds, %d meta" % (len(box), len(builds), len(meta)))


if __name__ == "__main__":
    main()
