#!/usr/bin/env python3
"""Smogon's written analyses, shaped for the app.

    python scripts/build_analysis_data.py     -> tracker/analysis.js

The only source in this project with REASONING in it. 54 Pokemon have a written
VGC analysis: the sets people actually run, the SP spread and what each point
of it survives, which Pokemon check it, which partners cover its holes. It has
been downloaded every night since the project started and read only through
`query.py pokemon` on the laptop - never on the phone, which is where the
decisions get made.

IT IS ITS OWN ASSET, AND LOADED ONLY WHEN ASKED. Trimmed it is 407 KB against a
dex payload of 419: doubling what the phone downloads every time the dex moves,
for a panel that is opened occasionally, is the wrong trade. It is fetched the
first time a sheet asks for it and cached immutably by its content hash after
that.

What is dropped: the learnset (the app has its own), the base stats (same), and
Smogon's own name for the Pokemon where it matches ours. What is kept is the
prose, because the prose is the thing that cannot be derived.
"""
import io, json, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "data", "meta", "smogon_analyses.json")
OUT = os.path.join(ROOT, "tracker", "analysis.js")


def main():
    if not os.path.exists(SRC):
        sys.exit("no analyses yet - run scripts/fetch_smogon.py")
    blob = json.load(io.open(SRC, encoding="utf-8"))
    out = {}
    for mon in blob.get("pokemon") or []:
        strategies = mon.get("vgc_strategies") or []
        if not strategies:
            continue
        got = []
        for st in strategies:
            sets = []
            for ms in st.get("movesets") or []:
                sets.append({
                    "name": ms.get("name") or "",
                    "ability": ms.get("abilities") or [],
                    "item": ms.get("items") or [],
                    "nature": ms.get("natures") or [],
                    # Champions calls them SP, and the spread is the half of a
                    # set that cannot be guessed from the moves
                    "sp": ms.get("stat_points") or [],
                    "moves": ms.get("moveslots") or [],
                    "why": ms.get("explanation") or "",
                })
            if not sets and not (st.get("overview") or "").strip():
                continue
            got.append({
                "format": st.get("format") or "",
                # a format Smogon has marked as out of date still says what a
                # Pokemon is FOR, so it is kept and labelled rather than hidden
                "outdated": bool(st.get("outdated")),
                "overview": st.get("overview") or "",
                "sets": sets,
                "credits": st.get("credits") or [],
            })
        if got:
            out[mon.get("name")] = got

    body = ("/* GENERATED by scripts/build_analysis_data.py - do not edit.\n"
            "   Smogon's written VGC analyses, the only source here with\n"
            "   reasoning in it. Loaded on demand, never on page load. */\n"
            "window.CHAMP_ANALYSIS = "
            + json.dumps(out, ensure_ascii=False, separators=(",", ":"))
            + ";\n")
    with io.open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(body)
    sets = sum(len(s["sets"]) for v in out.values() for s in v)
    print("wrote %s  (%d KB, %d Pokemon, %d sets)"
          % (OUT, len(body.encode("utf-8")) // 1024, len(out), sets))
    return 0


if __name__ == "__main__":
    sys.exit(main())
