#!/usr/bin/env python3
"""Bundle Smogon's own Champions engine for the browser.

    python scripts/build_engine_bundle.py

The calculator in the tracker does not approximate the engine - it IS the
engine. A hand port drifts: the modifier chain runs in four separate buckets
(base power, attack, defence, final), each chained in 4096-space with its own
rounding step, and getting one stage wrong costs a point. One point can flip a
2HKO into a 3HKO, which is the only thing the player counts.

So the vendored `data/raw/smogon_calc/calc/` is bundled with esbuild and inlined
into the page. Re-run this after `fetch_smogon_calc.py` reports upstream moved
and the page picks up the same fix Smogon shipped.

calc.js is deliberately not the entry point: it requires every generation's
mechanics, and the vendored copy only carries champions.js.
"""
import json, os, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CALC = os.path.join(ROOT, "data", "raw", "smogon_calc", "calc")
ENTRY = os.path.join(CALC, "__entry.js")
OUT = os.path.join(ROOT, "tracker", "engine.bundle.js")

ENTRY_SRC = """// GENERATED by scripts/build_engine_bundle.py - do not edit.
// The same five modules scripts/smogon_engine.js loads, exposed to the page.
var Generations = require("./data/index").Generations;
var Pokemon = require("./pokemon").Pokemon;
var Move = require("./move").Move;
var Field = require("./field").Field;
var calculateChampions = require("./mechanics/champions").calculateChampions;
globalThis.SMOGON = {
  gen: Generations.get(0),        // Champions is generation 0 in this bundle
  Pokemon: Pokemon, Move: Move, Field: Field,
  calculate: calculateChampions
};
"""


def main():
    if not os.path.isdir(CALC):
        sys.exit("the engine is not vendored - run scripts/fetch_smogon_calc.py")
    with open(ENTRY, "w", encoding="utf-8") as f:
        f.write(ENTRY_SRC)
    # The PINNED esbuild from node_modules, never `npx esbuild`. npx fetches
    # whatever is newest at the moment it runs - unversioned, unreviewed, and
    # in CI too - to build a file that then goes straight onto the phone. The
    # version is in package-lock.json and `npm ci` installs exactly it, which
    # is the same rule supabase-js follows for the same reason.
    esb = os.path.join(ROOT, "node_modules", ".bin",
                       "esbuild.cmd" if os.name == "nt" else "esbuild")
    if not os.path.exists(esb):
        sys.exit("esbuild is not installed - run `npm ci`. Looked in %s" % esb)
    r = subprocess.run([esb, ENTRY, "--bundle", "--format=iife",
                        "--minify", "--outfile=" + OUT],
                       capture_output=True, text=True, cwd=ROOT)
    if r.returncode != 0:
        sys.exit("esbuild failed:\n" + (r.stderr or r.stdout))
    size = os.path.getsize(OUT)
    print("wrote %s  (%.0f KB)" % (OUT, size / 1024))

    # a bundle that does not answer is worse than none, so prove it runs
    check = subprocess.run(
        ["node", "-e",
         "require(%s);const S=globalThis.SMOGON;"
         "const a=new S.Pokemon(S.gen,'Garchomp',{evs:{atk:32}});"
         "const d=new S.Pokemon(S.gen,'Kingambit',{});"
         "const m=new S.Move(S.gen,'Earthquake');"
         "const f=new S.Field({gameType:'Singles'});"
         "const r=S.calculate(S.gen,a,d,m,f);"
         "const x=[].concat.apply([],r.damage);"
         "console.log(Math.min.apply(null,x)+'-'+Math.max.apply(null,x));"
         % json.dumps(OUT.replace("\\", "/"))],
        capture_output=True, text=True, cwd=ROOT)
    got = (check.stdout or "").strip()
    if check.returncode != 0 or not got:
        sys.exit("the bundle does not run:\n" + (check.stderr or ""))
    print("  smoke test - Garchomp Earthquake vs Kingambit (singles): %s" % got)
    if got != "150-176":
        print("  NOTE: expected 150-176. The engine may have been updated; "
              "check scripts/damage.py --selftest before trusting it.")


if __name__ == "__main__":
    main()
