#!/usr/bin/env python3
"""What each Pokemon's own players run, shaped for the app.

    python scripts/build_splits_data.py     -> tracker/splits.js

data/meta/usage_splits.json holds everything pokebase's per-Pokemon pages give.
The app needs the head of each list, not the tail: nobody building a Kingambit
needs the move 0.2% of them run, and the difference is 494 KB against 206.

IT IS ITS OWN ASSET, AND THAT IS THE POINT. The dex is rebuilt every night
because ladder usage moves every night; these splits are fetched WEEKLY,
because 321 pages at 1.3 MB is six minutes of someone else's bandwidth. Keeping
them in the dex would make a nightly refresh re-download 206 KB that had not
changed. Grouped by how often they change, they are fetched once a week and
cached for a year.
"""
import io, json, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "data", "meta", "usage_splits.json")
OUT = os.path.join(ROOT, "tracker", "splits.js")

# How much of each list is worth carrying. A build has four move slots, one
# item, one ability and one nature, so the head is what a decision looks at.
KEEP = {"moves": 10, "items": 6, "abilities": 4, "natures": 4,
        "spreads": 5, "teammates": 6}


def main():
    if not os.path.exists(SRC):
        sys.exit("no splits yet - run scripts/fetch_pokebase_splits.py")
    blob = json.load(io.open(SRC, encoding="utf-8"))
    mons = blob.get("pokemon") or {}
    out = {}
    for name, v in mons.items():
        row = {
            # [name, percent] pairs, which is half the bytes of an object and
            # exactly as readable at the one place that unpacks them
            "m": [[x["name"], x["percent"]] for x in v.get("moves") or []][:KEEP["moves"]],
            "i": [[x["name"], x["percent"]] for x in v.get("items") or []][:KEEP["items"]],
            "a": [[x["name"], x["percent"]] for x in v.get("abilities") or []][:KEEP["abilities"]],
            "n": [[x["name"], x["percent"]] for x in v.get("natures") or []][:KEEP["natures"]],
            "s": [[x["sp"], x["percent"]] for x in v.get("spreads") or []][:KEEP["spreads"]],
            "t": (v.get("teammates") or [])[:KEEP["teammates"]],
        }
        if any(row.values()):
            out[name] = row

    body = ("/* GENERATED by scripts/build_splits_data.py - do not edit.\n"
            "   Of the people running THIS Pokemon, what they run: moves,\n"
            "   item, ability, nature and SP spread, with percentages, off\n"
            "   pokebase's live ladder. Fetched weekly, so it is its own\n"
            "   asset rather than riding on the nightly dex. */\n"
            "window.CHAMP_SPLITS = "
            + json.dumps(out, ensure_ascii=False, separators=(",", ":"))
            + ";\n")
    with io.open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(body)
    print("wrote %s  (%d KB, %d Pokemon, fetched %s)"
          % (OUT, len(body.encode("utf-8")) // 1024, len(out),
             blob.get("fetched", "?")))
    return 0


if __name__ == "__main__":
    sys.exit(main())
