#!/usr/bin/env python3
"""Link tracker/src/ and tracker/data.js into the page the phone loads.

Three jobs, in this order:

  link()          resolves the app's ES modules into one script. The parts
                  under tracker/src/ import and export like any other modern
                  JavaScript; esbuild does the linking at BUILD time, so what
                  the browser gets is still one plain <script>. Why not let the
                  browser link them itself is answered above ESBUILD below, and
                  the short version is that jsdom cannot run module scripts and
                  the whole browser half of the gate does.

  assemble()      drops that script, the stylesheet and the markup into
                  index.template.html, a 23-line shell of markers.

  build_dist()    splits the result back out into the files Cloudflare serves.

Two shapes come out of it, and the difference is delivery, not code.

`tracker/index.html` is the single page, everything inlined. That was the
original constraint - an artifact serves exactly one file - and it is still the
right answer anywhere nothing else can be served alongside it.

`tracker/dist/` is what Cloudflare gets: a 51 KB shell pointing at four hashed
assets, plus the app's sourcemap. Same program, cached in pieces that change at
different rates, so a nightly dex refresh costs 347 KB instead of 1,314. See
split_assets().
"""
import hashlib, json, os, re, shutil, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TPL = os.path.join(ROOT, "tracker", "index.template.html")
DATA = os.path.join(ROOT, "tracker", "data.js")
CFG = os.path.join(ROOT, "tracker", "config.local.json")
OUT = os.path.join(ROOT, "tracker", "index.html")
DIST = os.path.join(ROOT, "tracker", "dist")
SRC = os.path.join(ROOT, "tracker", "src")
# Where the module link is done and its result can be read. Gitignored: every
# byte in it is generated, and both CI and any local run rebuild it.
BUILD = os.path.join(ROOT, "tracker", "build")
MARK = "/*__CHAMP_DATA__*/"
# Filled in during the build, read when the headers are written:
# only the Supabase URL, and only so the CSP names the same host.
BUILT = {}
CMARK = "/*__CHAMP_CONFIG__*/"
EMARK = "/*__CHAMP_ENGINE__*/"
ENGINE = os.path.join(ROOT, "tracker", "engine.bundle.js")
# supabase-js used to be a <script src> pointing at jsDelivr. It is inlined from
# node_modules now, which is the same 213 KB the browser downloaded either way -
# what changes is who can alter it. A CDN file is a third party in the runtime of
# a page that holds the whole ledger behind a login; SRI would have caught a
# tampered copy but leaves the dependency, and leaves a hash to keep in sync with
# a version by hand. From node_modules the lockfile pins the version, Dependabot
# moves it, and the CSP loses its last third-party origin.
SBMARK = "/*__CHAMP_SUPABASE__*/"
SBJS = os.path.join(ROOT, "node_modules", "@supabase", "supabase-js",
                    "dist", "umd", "supabase.js")
SMARK = "/*__CHAMP_STYLE__*/"
KMARK = "<!--__CHAMP_MARKUP__-->"
AMARK = "/*__CHAMP_APP__*/"


def parts():
    """The app's parts, in the order their number prefixes give.

    Only the numbered files. Anything starting with an underscore in
    tracker/src/ is generated by link() below, and reading one back as a part
    would compile the previous build into the next one.
    """
    got = sorted(f for f in os.listdir(SRC)
                 if f.endswith(".js") and not f.startswith("_"))
    if not got:
        sys.exit("tracker/src/ has no .js parts - the app would build empty")
    return got


def assemble(tpl):
    """Put tracker/src/ back together into the single script it has to be.

    The app was one 7,269-line file, which is not a file anyone can hold in
    their head: two views a thousand lines apart shared a helper and nothing
    said so, and every edit meant scrolling past nine other screens to reach
    the one being changed. So the pieces live under tracker/src/.

    They used to be CONCATENATED, which put every name back into one scope -
    the split bought readability and no safety at all. They are ES modules now
    and link() resolves the imports at build time. What arrives here is one
    script either way: the browser is handed the same single <script> it always
    was, because that is the artifact the browser tests load.
    """
    for m in (SMARK, KMARK, AMARK):
        if m not in tpl:
            sys.exit("the shell lost its %s marker" % m)
    css = open(os.path.join(SRC, "style.css"), encoding="utf-8").read()
    markup = open(os.path.join(SRC, "markup.html"), encoding="utf-8").read()
    tpl = tpl.replace(SMARK, css.rstrip(chr(10)))
    tpl = tpl.replace(KMARK, markup.rstrip(chr(10)))
    return tpl.replace(AMARK, link())


# THE APP'S PUBLIC SURFACE - the names that leave the bundle.
#
# Until the scoping pass every top-level name in 6,403 lines was a global by
# accident: thirteen parts concatenated into one script, so `byName` and `go`
# and `S` sat on `window` beside anything else that happened to be there, and
# nothing recorded which of them were meant to be reachable.
#
# This list is the surface, and it is derived from a real consumer rather than
# guessed: it is exactly what the browser tests reach for through `window`. The
# markup needs none of it - it has no inline handlers at all, only an
# aria-controls attribute, checked.
#
# CHAMP and SMOGON are NOT here: the tests read them, but the dex and the engine
# put them on window themselves, from their own scripts. The app only consumes
# them, so closing the app over its names never touched them.
PUBLIC = [
    "AB_SET", "CALC", "DEX", "MOVE_BY", "S", "TYPE_COLOR",
    "abilityTag", "buildLink", "buildSheet", "buildsPane", "byName",
    "closeSheet", "engineCalc", "findDetail", "go", "gtsPickMine", "learnset",
    "megasFor", "moveRowFor", "pokeSheet", "teamReport", "teamSheet",
    "teamTypes",
]

# WHY A BUNDLER AT ALL, when the source is standard ES modules that the browser
# could load by itself.
#
# Because jsdom does not execute <script type="module"> - measured, not
# assumed: a module script sets nothing while a classic one beside it runs. The
# browser tests load tracker/dist/index.html under jsdom, and three of them
# grep that page for the app's own source. Shipping module scripts would not
# have failed those tests, it would have made them pass by finding nothing,
# which is the worst way for a check to break. Keeping them would mean a real
# headless browser in the nightly job: a far larger dependency than this one,
# and a flakier gate.
#
# So the modules are linked here and the page is handed the same single script
# it has always been served. The tests then run on the exact bytes that deploy,
# which is worth more than any promise a build tool makes about itself.
#
# esbuild is PINNED in package-lock.json and installed by `npm ci` - never
# `npx esbuild`, which fetches whatever is newest at the moment it runs,
# including in CI.
ESBUILD = os.path.join(ROOT, "node_modules", ".bin",
                       "esbuild.cmd" if os.name == "nt" else "esbuild")

LEGACY = os.path.join(SRC, "_legacy.js")
ENTRY = os.path.join(SRC, "_entry.js")


def surface(text):
    """(what this part exports, what it imports and from where).

    Both are read off the part's own import/export statements, which are
    hand-written - this never guesses at a declaration.
    """
    exports = []
    for block in re.findall(r"^export\s*\{([^}]*)\}", text, re.M):
        exports += [n.strip() for n in block.split(",") if n.strip()]
    imports = {}
    pat = r"""^import\s*\{([^}]*)\}\s*from\s*['"]\./([^'"]+)['"]"""
    for names, src in re.findall(pat, text, re.M):
        imports.setdefault(src, []).extend(
            n.strip() for n in names.split(",") if n.strip())
    return exports, imports


def link():
    """Resolve the parts into one script, and say what is still unconverted.

    Two files are generated to do it, both into tracker/src/ so the relative
    imports in the hand-written parts resolve without rewriting a single
    specifier:

      _legacy.js  every part that is NOT a module yet, concatenated exactly as
                  before and wrapped as one module. It imports what the
                  converted modules export and exports what they - and the
                  entry - still need from it. It is the BRIDGE, and it loses a
                  part every time a part is converted. When it is empty the
                  pass is over and it stops being generated.

      _entry.js   imports the PUBLIC names from wherever they now live and
                  publishes them on window. The only place the app touches the
                  global object.
    """
    if not os.path.exists(ESBUILD):
        sys.exit("esbuild is not installed - run `npm ci`. Looked in %s"
                 % ESBUILD)
    mods, pile = [], []
    for f in parts():
        text = open(os.path.join(SRC, f), encoding="utf-8").read()
        (mods if re.search(r"^(?:import|export)\s", text, re.M)
         else pile).append((f, text))

    owner = {}                      # exported name -> the file that exports it
    from_legacy = []                # what the modules still need from the pile
    for f, text in mods:
        exports, imports = surface(text)
        for n in exports:
            if n in owner:
                sys.exit("%s and %s both export %s" % (owner[n], f, n))
            owner[n] = f
        from_legacy += imports.get("_legacy.js", [])

    pile_text = "".join(t for _, t in pile)
    # Every name the modules export is imported into the bridge, used or not.
    # Working out the subset the pile actually references would mean scanning
    # thousands of lines of JavaScript with a regex, and being wrong about one
    # name is a ReferenceError on load. An unused import costs nothing, while a
    # name the pile ALSO declares is a real collision that esbuild refuses to
    # build - which is the answer we want.
    head = ["/* GENERATED by scripts/build_tracker_page.py - do not edit.",
            "   The parts that are not ES modules yet, concatenated as they",
            "   always were and wrapped as one module so the converted ones can",
            "   import from them. Convert a part and it leaves this file. */"]
    for f, text in mods:
        got = surface(text)[0]
        if got:
            head.append('import {%s} from "./%s";' % (", ".join(got), f))

    # What the bridge has to hand back: whatever the modules import from it,
    # plus every PUBLIC name no module owns - those are still declared in the
    # pile, and the entry has to be able to import them.
    out = sorted(set(from_legacy) | set(n for n in PUBLIC if n not in owner))
    missing = [n for n in out if not re.search(
        r"\b(?:function|var|let|const)\s+%s\b" % n, pile_text)]
    if missing:
        # Converting a part moves its names OUT of the pile, and any module
        # that was reaching them through the bridge has to be pointed at the
        # real file. That is the ordinary next step of the pass, not a bug, so
        # the message says which file to name rather than just what is absent.
        moved = [(n, owner[n]) for n in missing if n in owner]
        if moved:
            sys.exit("no longer in the bridge: %s. Import %s from there "
                     "instead of \"./_legacy.js\"."
                     % (", ".join("%s (now %s)" % m for m in moved),
                        "it" if len(moved) == 1 else "them"))
        sys.exit("nothing in tracker/src/ declares: %s" % ", ".join(missing))
    tail = ["", "/* what the converted modules and the entry still take from "
            "this pile */", "export {%s};" % ", ".join(out), ""]
    write(LEGACY, chr(10).join(head) + chr(10) + pile_text.rstrip(chr(10))
          + chr(10) + chr(10).join(tail))

    by_file = {}
    for n in PUBLIC:
        by_file.setdefault(owner.get(n, "_legacy.js"), []).append(n)
    entry = ["/* GENERATED by scripts/build_tracker_page.py - do not edit.",
             "   The app's one deliberate contact with the global object. The",
             "   list is PUBLIC in that script, and a name here that its module",
             "   does not export is an esbuild error, not a blank page. */"]
    if pile:
        # THE BRIDGE IS IMPORTED FIRST, and the order is the whole point.
        #
        # A module's body runs when the graph reaches it, and the entry's
        # imports are walked depth-first in the order they are written. Import
        # 04-nav before the bridge and the walk goes entry -> 04-nav -> bridge
        # (04-nav needs three redraws from it), so the BRIDGE's body runs first
        # and 13-boot's startup calls buildTabs() before 04-nav has built TABS.
        # Which is exactly what happened: sixteen browser tests failed at once
        # with `Cannot read properties of undefined`.
        #
        # Entering through the bridge fixes it by construction. The bridge
        # imports every converted module at its top, in numeric order, so the
        # walk emits them in that order and the bridge's own body - which ends
        # in 13-boot, the code that starts the app - runs after all of them.
        # That is the order the parts had when they were concatenated.
        #
        # Not a bundler quirk: this is what the language does with a cycle, and
        # native modules would do the same. check_order() below asserts it held.
        entry.append('import "./_legacy.js";')
    for f in sorted(by_file):
        entry.append('import {%s} from "./%s";'
                     % (", ".join(sorted(by_file[f])), f))
    entry.append("Object.assign(window, {")
    entry += ["  %s: %s," % (n, n) for n in PUBLIC]
    entry.append("});")
    write(ENTRY, chr(10).join(entry) + chr(10))

    if not os.path.isdir(BUILD):
        os.makedirs(BUILD)
    out_js = os.path.join(BUILD, "app.js")
    r = subprocess.run(
        [ESBUILD, ENTRY, "--bundle", "--format=iife", "--target=es2017",
         # esbuild escapes non-ASCII by default, which would turn every bullet,
         # arrow and accent in the app into six bytes of noise
         "--charset=utf8",
         # external: no sourceMappingURL comment is appended, because the file
         # has to hash to the name it is served under. _headers points at the
         # map with a SourceMap: header instead.
         "--sourcemap=external", "--outfile=" + out_js],
        capture_output=True, text=True, cwd=ROOT)
    if r.returncode != 0:
        sys.exit("esbuild could not link the app:" + chr(10)
                 + (r.stderr or r.stdout))
    js = open(out_js, encoding="utf-8").read()
    check_order(js, [f for f, _ in mods], bool(pile))
    BUILT["app_map"] = open(out_js + ".map", encoding="utf-8").read()
    print("  app: %d module%s linked, %d part%s still in the bridge, %.0f KB"
          % (len(mods), "" if len(mods) == 1 else "s", len(pile),
             "" if len(pile) == 1 else "s", len(js) / 1024))
    return js.rstrip(chr(10))


def check_order(js, mods, has_bridge):
    """Every module's body ran before the bridge's, which starts the app.

    An app whose parts execute in the wrong order does not fail where it is
    wrong - it fails wherever the first name is read too early, with a message
    that names neither file. Sixteen tests went red at once for it and the
    stack said `buildTabs`. So it is asserted here, where the answer is one
    line long.

    Only that one ordering is required, and it is required absolutely: the
    bridge ends in 13-boot, whose top-level statements build the tab bar and
    draw the first screen, so anything it touches has to exist by then.

    Among the modules themselves the order is whatever the import graph says,
    and that is the improvement: 05-box runs after 09-gts because it imports
    boxBadges from it, not because of a number in a filename. Nothing depends
    on the old concatenation order any more - the only top-level statements
    left in the converted parts attach handlers to their own elements.

    esbuild writes a `// tracker/src/<part>` comment above each module body,
    which is what makes this readable. If it ever stops, the count check fails
    rather than the whole thing passing silently.
    """
    seen = re.findall(r"^\s*// tracker/src/(\S+)$", js, re.M)
    want = len(mods) + (1 if has_bridge else 0) + 1        # + the entry
    if len(seen) != want:
        sys.exit("cannot read the link order out of the bundle: expected %d "
                 "module markers, found %d" % (want, len(seen)))
    print("  link order: %s" % " ".join(f.replace(".js", "") for f in seen
                                        if f != "_entry.js"))
    if not has_bridge:
        return
    after = [f for f in seen[seen.index("_legacy.js"):] if f in mods]
    if after:
        sys.exit("%s runs AFTER the bridge, so 13-boot would start the app "
                 "before that part had built anything. The entry must import "
                 "./_legacy.js first." % ", ".join(after))


def write(path, text):
    """LF, always. A generated file whose line endings differ between this
    machine and CI changes the bundle, and the bundle's name is its hash."""
    open(path, "w", encoding="utf-8", newline="").write(text)


def config_js():
    """The Supabase endpoint, or nothing.

    The publishable key belongs in the page: the browser needs it to speak to
    PostgREST at all, and Supabase publishes it for exactly that. What keeps
    the data private is Row Level Security plus the sign-in, not hiding this
    string. A secret / service_role key must NEVER end up here - it bypasses
    RLS, and this file is meant to be served to anyone.
    """
    # CI has no config.local.json - it is gitignored, because it is per
    # machine. Without a fallback the build would quietly succeed and deploy a
    # page with CHAMP_CONFIG = {}, i.e. the app with its ledger disconnected.
    # Silent, and worse than failing. Environment first, then the file.
    env_url = os.environ.get("SUPABASE_URL")
    env_key = os.environ.get("SUPABASE_PUBLISHABLE_KEY")
    if env_url and env_key:
        c = {"url": env_url, "publishableKey": env_key,
             "loginEmail": os.environ.get("SUPABASE_LOGIN_EMAIL", "")}
        print("  Supabase: from the environment")
    elif not os.path.exists(CFG):
        print("  no tracker/config.local.json - building the Claude-db version")
        return "window.CHAMP_CONFIG = {};"
    else:
        c = json.load(open(CFG, encoding="utf-8"))
    for k in ("url", "publishableKey"):
        if not c.get(k):
            sys.exit("config.local.json is missing %s" % k)
    for k, v in c.items():
        s = str(v)
        if "service_role" in s or s.startswith("sb_secret"):
            sys.exit("config.local.json holds a SECRET key (%s). Remove it and "
                     "rotate that key - it must never be built into the page." % k)
    print("  Supabase: %s" % c["url"])
    # Remembered for the Content-Security-Policy. The policy has to name the exact
    # host the page was built to talk to, and resolving it twice is how the two
    # would drift: the day the project URL moves, a second copy keeps pointing at
    # the old one and the app looks broken with no error, just a blocked request.
    BUILT["supabase"] = c["url"]
    return "window.CHAMP_CONFIG = " + json.dumps(
        {"supabase": {"url": c["url"], "key": c["publishableKey"],
                      "email": c.get("loginEmail", "")}},
        ensure_ascii=False) + ";"


def headers(supabase_url, assets=()):
    """What the page may load, and above all where it may SEND.

    Derived from the page's measured surface, not guessed:
      - one external script, supabase-js from jsDelivr
      - the IBM Plex stylesheet from fonts.googleapis.com, its files from
        fonts.gstatic.com
      - Supabase over https for REST and auth, and over wss for realtime
      - a same-origin fetch of the page itself, which is how the search view
        probes whether it is online
      - photographs held as data:/blob: while a box scan is confirmed
    Nothing in tracker/src/ or the vendored engine uses eval or new Function -
    both checked - so no 'unsafe-eval' is needed.

    `script-src` does carry 'unsafe-inline', and that is the price of the single
    page: the whole app is inline, so there is no origin to allow instead. A hash
    per block was considered and rejected - five of them, recomputed every build,
    where one whitespace difference serves a blank screen.

    That trade is fair because the attack this closes is not inline script, it is
    exfiltration. The page holds the entire ledger behind a login, and the one
    piece of code on it that nobody here wrote is fetched from a CDN. `connect-src`
    means a tampered supabase.js can read the ledger and has nowhere to send it:
    one Supabase project, and the page's own origin.
    """
    csp = [
        "default-src 'self'",
        # no third-party origin at all: supabase-js is inlined from
        # node_modules, so the only script on the page is the page
        "script-src 'self' 'unsafe-inline'",
        "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
        "font-src https://fonts.gstatic.com",
        "img-src 'self' data: blob:",
        "object-src 'none'",
        "base-uri 'none'",
        # there is exactly one real <form> on the page, the login
        "form-action 'self'",
        "frame-ancestors 'none'",
    ]
    send = ["'self'"]
    if supabase_url:
        host = supabase_url.rstrip("/")
        send += [host, "wss://" + host.split("://", 1)[-1]]
    else:
        # the Claude-db build has no Supabase host to allow, and saying so beats
        # shipping a policy that quietly permits nothing
        print("  CSP: no Supabase host - connect-src is same-origin only")
    csp.insert(1, "connect-src " + " ".join(send))
    # A hashed name can never mean anything else, so it is cached for a year
    # and never revalidated. index.html is the opposite: it is the pointer to
    # which hashes are current, so it must be re-checked on every load or a
    # new deploy stays invisible until something evicts it.
    rules = ""
    for a in assets:
        rules += "/%s\n  Cache-Control: public, max-age=31536000, immutable\n" % a
        # Pointed at by a HEADER rather than a //# sourceMappingURL comment
        # inside the file: the asset name is a hash of its bytes, and a
        # comment naming a file whose name depends on those bytes cannot be
        # written without breaking that promise at one end or the other.
        if a == BUILT.get("app_asset"):
            rules += "  SourceMap: /%s.map\n" % a
        rules += "\n"
    rules += "/%s.map\n  Cache-Control: public, max-age=31536000, immutable\n\n" % BUILT["app_asset"]
    rules += "/index.html\n  Cache-Control: no-cache\n\n/\n  Cache-Control: no-cache\n\n"
    open(os.path.join(DIST, "_headers"), "w", encoding="utf-8").write(rules +
        "/*\n"
        "  X-Content-Type-Options: nosniff\n"
        "  Referrer-Policy: no-referrer\n"
        "  X-Frame-Options: DENY\n"
        "  Content-Security-Policy: " + "; ".join(csp) + "\n")


def main():
    if not os.path.exists(DATA):
        sys.exit("tracker/data.js is missing - run scripts/build_tracker_data.py")
    tpl = assemble(open(TPL, encoding="utf-8").read())
    for m in (MARK, CMARK, EMARK, SBMARK):
        if m not in tpl:
            sys.exit("the template lost its %s marker" % m)
    data = open(DATA, encoding="utf-8").read()
    # a literal </script> inside either blob would end the tag early
    if not os.path.exists(SBJS):
        # Never fall back to the CDN: a page that silently reaches out again is
        # the one thing this change exists to prevent.
        sys.exit("supabase-js is not installed - run `npm ci`. Looked in %s"
                 % SBJS)
    if not os.path.exists(ENGINE):
        sys.exit("tracker/engine.bundle.js is missing - run "
                 "scripts/build_engine_bundle.py")
    engine = open(ENGINE, encoding="utf-8").read()
    print("  engine bundle: %.0f KB" % (len(engine) / 1024))
    import datetime
    stamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    tpl = tpl.replace("/*__CHAMP_BUILD__*/",
                      "window.CHAMP_BUILD = %r;" % stamp)
    out = tpl.replace(EMARK, engine.replace("</", r"<\/"))
    sbjs = open(SBJS, encoding="utf-8").read()
    out = out.replace(SBMARK, sbjs.replace("</", r"<\/"))
    out = out.replace(CMARK, config_js().replace("</", r"<\/"))
    out = out.replace(MARK, data.replace("</", r"<\/"))
    open(OUT, "w", encoding="utf-8").write(out)
    print("wrote %s  (%.0f KB)" % (OUT, os.path.getsize(OUT) / 1024))
    build_dist(out)


def standalone(html):
    """Wrap the artifact-shaped fragment into a real HTML document.

    The Claude artifact viewer supplies the skeleton - doctype, charset,
    viewport and a small reset - so the published file is written without one.
    Served from anywhere else that skeleton is simply absent, and three things
    break at once:

      * no <meta charset>: the browser guesses, and every em dash, ×, ·, → and
        the ellipsis in "Signing in..." renders as mojibake
      * no <meta viewport>: the phone lays the page out at desktop width
      * no [hidden]{display:none!important}: the UA default loses to any author
        rule that sets display, so .sheetfoot stays visible when hidden is set

    Everything up to the first </style> is head material; the rest is body.
    """
    cut = html.index("</style>") + len("</style>")
    head, body = html[:cut], html[cut:]
    return (
        "<!doctype html>\n"
        '<html lang="en">\n'
        "<head>\n"
        '<meta charset="utf-8">\n'
        '<meta name="viewport" content="width=device-width,initial-scale=1,'
        'viewport-fit=cover">\n'
        '<meta name="color-scheme" content="light dark">\n'
        "<style>html{color-scheme:light dark}body{margin:0}"
        "img{max-width:100%}[hidden]{display:none!important}</style>\n"
        + head + "\n</head>\n<body>\n" + body + "\n</body>\n</html>\n")


# WHICH BLOCKS LEAVE THE PAGE, and why each earns its own file: they change at
# completely different rates. The dex is rewritten every night, the app when it
# is edited, the engine only when Smogon ships one, the library on a version
# bump. Inlined together they were one artifact, so a single usage number moving
# overnight made the phone re-download all 1,314 KB - engine and library
# included, neither of which had changed.
#
# The filename carries a hash of the content, so a changed file is a NEW url and
# an unchanged one is never fetched again. _headers marks those immutable, which
# is what makes the split pay: without it the browser still revalidates every
# asset on every load, and the saving is a round trip rather than a download.
#
# index.html stays small and deliberately uncached: it is the pointer saying
# which hashes are current, so it has to be allowed to change.
SPLIT = ["vendor-supabase", "engine", "dex", "app"]


def split_assets(html):
    """Move the four big inline blocks into their own files.

    -> (html carrying <script src> tags, {filename: text})
    """
    assets = {}
    for ident in SPLIT:
        open_tag = '<script id="%s">' % ident
        if open_tag not in html:
            sys.exit("the page lost its %s block - split_assets cannot run"
                     % ident)
        i = html.index(open_tag)
        j = html.index("</script>", i)
        body = html[i + len(open_tag):j]
        # The inline form escapes </ so a literal </script> inside the code
        # cannot close the tag early. A separate file has no such constraint and
        # must carry the original text, or the code is not the code any more.
        body = body.replace(r"<\/", "</")
        name = "%s.%s.js" % (
            ident, hashlib.sha256(body.encode("utf-8")).hexdigest()[:8])
        assets[name] = body
        html = (html[:i] + '<script src="%s"></script>' % name
                + html[j + len("</script>"):])
    return html, assets


def build_dist(html):
    """tracker/dist/ is the ONLY directory that may be deployed.

    tracker/ holds config.local.json, the template, and - whenever
    anyone has left a supabase_seed.sql there - every Pokemon and every build
    in plaintext. Nothing generates one any more, but the reasoning stands and
    applies equally to a backup snapshot dropped in the wrong place: serving
    the folder would put the whole ledger on a public URL and undo the Row
    Level Security it took to keep it private. The deploy
    target is built from scratch here and contains nothing that was not put in
    deliberately.
    """
    import shutil
    if os.path.isdir(DIST):
        shutil.rmtree(DIST)
    os.makedirs(DIST)

    page, assets = split_assets(standalone(html))
    # newline="" on every one of these. Without it Python translates each
    # line ending on Windows, so the file written at app.<hash>.js does not
    # hash to <hash> - locally only, because CI is Linux. A name that is a
    # promise about the bytes has to be kept on both.
    for name, text in sorted(assets.items()):
        open(os.path.join(DIST, name), "w", encoding="utf-8",
             newline="").write(text)
        print("  asset %-30s %6.0f KB" % (name, len(text) / 1024))
    open(os.path.join(DIST, "index.html"), "w", encoding="utf-8",
         newline="").write(page)
    # The app is LINKED from thirteen files now, so the deployed bytes are no
    # longer the bytes anyone wrote: esbuild reprints them and drops the
    # comments. The map is how a stack trace on the phone still points at
    # tracker/src/09-gts.js and a line a person can read. It is named after the
    # asset's own hash, gets the same immutable lifetime, and is only ever
    # fetched with devtools open.
    app = [n for n in assets if n.startswith("app.")]
    if len(app) != 1:
        sys.exit("expected exactly one app asset, got %s" % sorted(app))
    BUILT["app_asset"] = app[0]
    open(os.path.join(DIST, app[0] + ".map"), "w", encoding="utf-8",
         newline="").write(BUILT["app_map"])

    manifest = {
        "name": "Champions Ledger",
        "short_name": "Ledger",
        "start_url": "./",
        "scope": "./",
        "display": "standalone",
        "background_color": "#0A1012",
        "theme_color": "#0A1012",
        # the two purposes are declared separately on purpose: a maskable
        # icon is drawn to be CROPPED to the system shape, so offering the
        # same file as "any" lets a browser show the cropped-for design
        # uncropped, and the other way round eats the mark.
        "icons": ([{"src": "icon-%d.png" % s, "sizes": "%dx%d" % (s, s),
                    "type": "image/png", "purpose": "any"} for s in (192, 512)]
                  + [{"src": "icon-%d.png" % s, "sizes": "%dx%d" % (s, s),
                      "type": "image/png", "purpose": "maskable"}
                     for s in (192, 512)]),
    }
    with open(os.path.join(DIST, "manifest.webmanifest"), "w",
              encoding="utf-8") as f:
        json.dump(manifest, f, indent=2)
    icons()

    # belt and braces: nothing may reach dist/ that was not written above
    allowed = ({"index.html", "manifest.webmanifest", "icon-192.png",
                "icon-512.png", "apple-touch-icon.png", "_headers",
                BUILT["app_asset"] + ".map"} | set(assets))
    # Every asset the page names must exist, or the deploy is a page that loads
    # nothing. That is the failure this split introduces, so it is checked here
    # rather than discovered on the phone.
    for name in assets:
        if ('src="%s"' % name) not in page:
            sys.exit("dist/%s was written but the page never references it"
                     % name)
    stray = set(os.listdir(DIST)) - allowed
    if stray:
        sys.exit("dist/ picked up unexpected files: %s" % sorted(stray))

    headers(BUILT.get("supabase"), sorted(assets))

    total = sum(os.path.getsize(os.path.join(DIST, f))
                for f in os.listdir(DIST))
    print("wrote %s  (%d files, %.0f KB) - this is the deploy directory"
          % (DIST, len(os.listdir(DIST)), total / 1024))


TEAL = (51, 192, 173, 255)
INK = (8, 22, 24, 255)
AMBER = (224, 164, 76, 255)


def icons():
    """The mark: a dark C-ring on full teal, with one amber slot in its gap.

    History, so neither mistake comes back. v1 drew a dark frame on the app's
    near-black ground: on a phone home screen that is an invisible black
    square, and the player reported the app as having "no icon". v2 went full
    bleed and readable, but the mark was three plain rounded rectangles, which
    he then called "un icono generico feo" (2026-09-11) - correct, it looked
    like any storage app.

    Three rules it follows now:

      * FULL BLEED and light. Teal ground, dark ink, so it reads against any
        wallpaper at launcher size.
      * The mark lives in the central 80%, the maskable safe zone. Android
        crops a maskable icon to a circle, squircle or teardrop, and anything
        on that line gets eaten.
      * It is a GLYPH, not a diagram. A C-ring is one shape the eye resolves
        at 48px; the amber slot in the gap is the app's own accent for "open",
        the same colour the box list uses for a slot that is not yours yet.
    """
    try:
        from PIL import Image, ImageDraw
    except ImportError:
        print("  (no PIL - skipping icons; the manifest will 404 on them)")
        return
    # drawn at 4x and downsampled: PIL has no antialiasing on arcs or
    # rounded rectangles, and at 192px the jaggies are plainly visible
    SS = 4
    for size in (192, 512, 180):
        S = size * SS
        img = Image.new("RGBA", (S, S), TEAL)
        d = ImageDraw.Draw(img)
        safe = S * 0.8
        cx = cy = S / 2
        r = safe * 0.40                    # ring radius, centre of the stroke
        t = safe * 0.17                    # stroke thickness
        box = [cx - r, cy - r, cx + r, cy + r]
        # open to the RIGHT, which is what makes it read as a C rather than an
        # O; the gap is wide enough to survive the downsample
        d.arc(box, start=38, end=322, fill=INK, width=int(t))
        # the open slot, sitting in the gap on the ring's own centre line
        sq = safe * 0.215
        sx, sy = cx + r, cy
        d.rounded_rectangle([sx - sq / 2, sy - sq / 2, sx + sq / 2, sy + sq / 2],
                            radius=sq * 0.28, fill=AMBER)
        img = img.resize((size, size), Image.LANCZOS)
        name = "apple-touch-icon.png" if size == 180 else "icon-%d.png" % size
        if size == 180:
            img = img.convert("RGB")       # iOS wants no alpha channel
        img.save(os.path.join(DIST, name))


if __name__ == "__main__":
    main()
