/* Checks the tracker's own script for the mistakes that keep reaching the
 * player. `node --check` catches none of these: they are all legal JavaScript
 * that simply does the wrong thing.
 *
 *   node scripts/check_app.js
 *
 * 1. A `var` declared twice in the same scope. Legal, and the second silently
 *    overwrites the first. It shipped: renderAll() had `var cap = capacity()`
 *    for the box limit and, ten lines later, `var cap = 12` for how many HOME
 *    rows to show - so the full-box warning read "48/12".
 *
 * 2. A CALC.* switch the screen sets that the engine never reads. That shipped
 *    too: a Life Orb toggle and a "Burned" toggle stayed on screen after the
 *    hand-written engine was replaced by Smogon's, looking like controls and
 *    doing nothing at all.
 *
 * 3. An element id the script reaches for that the markup does not contain.
 */
const fs = require("fs");
const path = require("path");

/* The app is thirteen files under tracker/src/ that the build links into one
   script, so the thing to check is what that LINK cannot: a name that two
   parts each declare, and - since the module pass started - a converted module
   reaching for a name it never imported. Read them in the same order the build
   does, and the markup beside them, which is where the element ids live.

   NUMBERED files only. tracker/src/_legacy.js and _entry.js are generated by
   the build out of these same parts, and reading them back would check the
   previous build twice over and report every name in it as a duplicate. */
const ROOT = path.dirname(__dirname);
const SRC = path.join(ROOT, "tracker", "src");
const src = fs.readFileSync(path.join(SRC, "markup.html"), "utf8");
const files = fs.readdirSync(SRC)
  .filter(f => /^\d/.test(f) && f.endsWith(".js")).sort();
const text = {};
files.forEach(f => { text[f] = fs.readFileSync(path.join(SRC, f), "utf8"); });
const app = files.map(f => text[f]).join("");

let problems = 0;
function fail(msg) { problems++; console.log("  " + msg); }

/* Brace depth, counted character by character. Counting how many "function("
   appear before a point is a running total, not a depth - the first version of
   this check did exactly that and missed the very bug it was written for.
   Strings and comments are skipped so a brace inside one cannot shift it. */
function declarations(code) {
  const out = [];
  let depth = 0, i = 0, scopeSeq = 0, pending = 0;
  const stack = [0];
  const NL = String.fromCharCode(10);
  while (i < code.length) {
    const c = code[i];
    if (c === '"' || c === "'" || c === "`") {
      const q = c;
      i++;
      while (i < code.length && code[i] !== q) {
        if (code[i] === "\\") i++;
        i++;
      }
      i++;
      continue;
    }
    if (c === "/" && code[i + 1] === "/") {
      while (i < code.length && code[i] !== NL) i++;
      continue;
    }
    if (c === "/" && code[i + 1] === "*") {
      const j = code.indexOf("*/", i);
      i = j < 0 ? code.length : j + 2;
      continue;
    }
    /* A new FUNCTION is a new scope, and two callbacks can sit at the same
       brace depth while being completely separate - which is why depth alone
       produced false positives on drawStones and gtsSheet. Each `function`
       keyword opens a scope id that its braces carry. */
    if (code.startsWith("function", i) && !/[\w$]/.test(code[i + 8] || "") &&
        (i === 0 || !/[\w$.]/.test(code[i - 1]))) {
      pending = ++scopeSeq;
      i += 8;
      continue;
    }
    if (c === "{") {
      depth++;
      stack.push(pending || stack[stack.length - 1] || 0);
      pending = 0;
      i++;
      continue;
    }
    if (c === "}") { depth--; stack.pop(); i++; continue; }
    if (code.startsWith("var ", i) && (i === 0 || !/[\w$.]/.test(code[i - 1]))) {
      const m = /^var\s+([A-Za-z_$][\w$]*)/.exec(code.slice(i));
      if (m) out.push({ name: m[1], scope: stack[stack.length - 1] });
    }
    i++;
  }
  return out;
}

console.log("duplicate var in the same scope");
{
  const fnRe = /\bfunction\s+(\w+)\s*\(/g;
  const bounds = [];
  let m;
  while ((m = fnRe.exec(app))) bounds.push([m.index, m[1]]);
  bounds.push([app.length, null]);
  for (let k = 0; k < bounds.length - 1; k++) {
    const name = bounds[k][1];
    const body = app.slice(bounds[k][0], bounds[k + 1][0]);
    const seen = new Set();
    for (const v of declarations(body)) {
      const key = v.name + "@" + v.scope;
      if (seen.has(key)) {
        fail(name + '(): "var ' + v.name + '" declared twice at the same ' +
             "scope - the second silently overwrites the first");
      }
      seen.add(key);
    }
  }
  if (!problems) console.log("  none");
}

console.log("CALC switches the engine ignores");
{
  const before = problems;
  const eng = app.slice(app.indexOf("function engineCalc()"),
                        app.indexOf("function calcSideCtl("));
  const set = new Set();
  for (const m2 of app.matchAll(/CALC\.([A-Za-z_$][\w$]*)\s*=[^=]/g)) set.add(m2[1]);
  const structural = new Set(["atk", "def", "move", "gameType"]);
  for (const k of [...set].sort()) {
    if (structural.has(k)) continue;
    if (!eng.includes("CALC." + k)) {
      fail("CALC." + k + " is set by the screen but never reaches the engine");
    }
  }
  if (problems === before) console.log("  none");
}

console.log("element ids used but not in the markup");
{
  const before = problems;
  const ids = new Set([...src.matchAll(/id="([^"]+)"/g)].map(m3 => m3[1]));
  const dynamic = new Set(["pkNote", "whoBtn", "atkBudget", "defBudget"]);
  for (const m4 of app.matchAll(/\$\("([^"]+)"\)/g)) {
    if (!ids.has(m4[1]) && !dynamic.has(m4[1])) {
      fail('$("' + m4[1] + '") has no matching id in the markup');
    }
  }
  if (problems === before) console.log("  none");
}

/* 4. A PART that reads a name another part exports without importing it.
 *
 * This is the one fault the module pass introduced, and no other check can see
 * it. esbuild does not complain: an identifier a module never declares or
 * imports is, by the rules of the language, a global - so it links cleanly and
 * throws ReferenceError on the phone, in whatever function happens to touch it
 * first. Before the pass there was nothing to get wrong, because every part
 * shared one scope.
 *
 * IT IS A REAL PARSE, and the first version was not. That one scanned with a
 * regex and skipped any name the file bound ANYWHERE, so one `var note` inside
 * one function in 09-gts hid every other use of `note` in the file - and the
 * missing import went to production, where the GTS panel threw the moment real
 * data arrived. The browser tests did not catch it either: their Supabase stub
 * returns no rows, so the branch that draws a note never ran.
 *
 * So: acorn, the scope chain built properly (function scopes for var and
 * function declarations, block scopes for let/const/class, parameters, catch
 * bindings, named function expressions, and hoisting into the right one), and
 * a name is free only where it really is free. A shadow shadows exactly what
 * it should, which is why `var S = window.SMOGON` inside one function in
 * 11-damage is not reported while the ledger's own `S` elsewhere would be.
 */
console.log("a part using a name it never imported");
{
  const before = problems;
  const acorn = require("acorn");

  function analyse(code) {
    const ast = acorn.parse(code, { ecmaVersion: 2022, sourceType: "module",
                                    locations: true });
    const scopes = [];
    const free = new Map();
    const imported = new Set();
    const push = fn => scopes.push({ vars: new Set(), fn: !!fn });
    const pop = () => scopes.pop();
    function declare(name, kind) {
      for (let i = scopes.length - 1; i >= 0; i--) {
        if (kind !== "var" || scopes[i].fn) { scopes[i].vars.add(name); return; }
      }
    }
    const known = name => scopes.some(s => s.vars.has(name)) || imported.has(name);
    function pattern(node, kind) {
      if (!node) return;
      if (node.type === "Identifier") return declare(node.name, kind);
      if (node.type === "ObjectPattern")
        return node.properties.forEach(pr =>
          pattern(pr.type === "RestElement" ? pr.argument : pr.value, kind));
      if (node.type === "ArrayPattern")
        return node.elements.forEach(e => pattern(e, kind));
      if (node.type === "RestElement") return pattern(node.argument, kind);
      if (node.type === "AssignmentPattern") return pattern(node.left, kind);
    }
    /* var and function declarations belong to the enclosing FUNCTION, however
       deeply nested in blocks they are written */
    function hoist(body) {
      (function walk(n) {
        if (!n || typeof n !== "object") return;
        if (Array.isArray(n)) return n.forEach(walk);
        if (n.type === "FunctionDeclaration") {
          if (n.id) declare(n.id.name, "var");
          return;
        }
        if (n.type === "FunctionExpression" || n.type === "ArrowFunctionExpression") return;
        if (n.type === "VariableDeclaration" && n.kind === "var")
          n.declarations.forEach(d => pattern(d.id, "var"));
        for (const k of Object.keys(n)) if (k !== "type") walk(n[k]);
      })(body);
    }

    push(true);
    ast.body.forEach(n => {
      if (n.type === "ImportDeclaration")
        n.specifiers.forEach(sp => imported.add(sp.local.name));
    });
    hoist(ast.body);

    (function visit(node, parent) {
      if (!node || typeof node !== "object") return;
      if (Array.isArray(node)) return node.forEach(n => visit(n, parent));
      if (!node.type) return;
      switch (node.type) {
        case "Identifier": {
          const p = parent || {};
          if (p.type === "MemberExpression" && p.property === node && !p.computed) return;
          if (p.type === "Property" && p.key === node && !p.computed) return;
          if (p.type === "LabeledStatement" || p.type === "BreakStatement" ||
              p.type === "ContinueStatement") return;
          if (!known(node.name) && !free.has(node.name))
            free.set(node.name, node.loc.start.line);
          return;
        }
        case "VariableDeclaration":
          node.declarations.forEach(d => { pattern(d.id, node.kind); visit(d.init, d); });
          return;
        case "FunctionDeclaration":
        case "FunctionExpression":
        case "ArrowFunctionExpression": {
          const named = node.type === "FunctionExpression" && node.id;
          if (named) { push(true); declare(node.id.name, "let"); }
          push(true);
          node.params.forEach(pp => pattern(pp, "var"));
          if (node.body.type === "BlockStatement") hoist(node.body.body);
          visit(node.body, node);
          pop();
          if (named) pop();
          return;
        }
        case "BlockStatement":
          push(false);
          node.body.forEach(n => {
            if (n.type === "FunctionDeclaration" && n.id) declare(n.id.name, "var");
          });
          node.body.forEach(n => visit(n, node));
          pop();
          return;
        case "CatchClause":
          push(false);
          pattern(node.param, "let");
          node.body.body.forEach(n => visit(n, node));
          pop();
          return;
        case "ImportDeclaration":
          return;
        default:
          for (const k of Object.keys(node)) {
            if (k === "type" || k === "loc" || k === "start" || k === "end") continue;
            visit(node[k], node);
          }
      }
    })(ast, null);
    return free;
  }

  const owner = {};
  for (const f of files) {
    for (const m of text[f].matchAll(/^export\s*\{([^}]*)\}/gm)) {
      m[1].split(",").forEach(n => n.trim() && (owner[n.trim()] = f));
    }
  }
  for (const f of files) {
    let free;
    try {
      free = analyse(text[f]);
    } catch (e) {
      fail(f + " does not parse as a module: " + e.message);
      continue;
    }
    for (const [name, line] of free) {
      if (owner[name] && owner[name] !== f) {
        fail(f + ":" + line + " uses " + name + ", which " + owner[name] +
             " exports, without importing it - that links fine and throws " +
             "on the phone");
      }
    }
  }
  if (problems === before) console.log("  none");
}

console.log("");
if (problems) {
  console.log(problems + " problem(s)");
  process.exit(1);
}
console.log("clean");
