#!/usr/bin/env python3
"""The three screens at once, in a real browser.

    python scripts/preview.py            # builds, serves, prints the URL
    python scripts/preview.py --no-build # serve what is already in dist

WHY THIS EXISTS, AND WHY IT IS NOT A WINDOW.

Resizing the browser window does not work on this machine: the player runs
**komorebi**, a tiling window manager, so it re-tiles the window and every
`resize` silently has no effect - the call reports success and `innerWidth`
stays whatever the tiling layout gave that pane. Measured 2026-09-16: the
window read 948 CSS px wide while the monitor was 1920x1200 physical at
DPR 1.25, i.e. **1536x960 CSS**. A layout "verified at 1920x1080" was
therefore verified at a width his browser never has.

An **iframe** has none of that problem. Media queries fire on the iframe's own
width, nothing outside the page can override it, and three of them side by side
show the three screens at the same moment instead of one after another - which
is how the player asked to see it ("veias varias resoluciones al mismo tiempo").

It also unregisters the service worker and empties the cache before the first
paint, because the app is a PWA: without that, a "test" can quietly be run
against the build before the one being tested.

Nothing here reaches the phone. The page is written into `tracker/dist/`, which
is regenerated by every build, so it cannot go stale and cannot ship.
"""
import argparse
import functools
import http.server
import pathlib
import socketserver
import subprocess
import sys
import webbrowser

ROOT = pathlib.Path(__file__).resolve().parent.parent
DIST = ROOT / "tracker" / "dist"
PORT = 8777

# (label, css width, css height). The first is the player's own monitor, and it
# is 1536 rather than 1920 for the reason in the docstring.
SIZES = [
    ("desktop 1080p @125%", 1536, 860),
    ("laptop 1366", 1366, 700),
    ("phone", 390, 780),
]

PAGE = """<!doctype html><meta charset="utf-8"><title>resolutions</title>
<style>
 html,body{margin:0;background:#15191a;color:#cfd8d7;
   font:12px "IBM Plex Mono",ui-monospace,monospace}
 h1{font-size:13px;letter-spacing:.08em;text-transform:uppercase;
    padding:10px 14px;margin:0;color:#8fa3a1;border-bottom:1px solid #263031}
 #board{display:flex;gap:14px;padding:14px;align-items:flex-start;
   overflow-x:auto}
 .pane{flex:0 0 auto}
 .cap{padding:4px 2px 6px;color:#8fa3a1}
 .cap b{color:#e6efee}
 iframe{border:1px solid #263031;border-radius:8px;display:block;background:#000}
 #bar{padding:0 14px 12px}
 button{font:inherit;background:#1e2526;color:#cfd8d7;border:1px solid #33403f;
   border-radius:6px;padding:5px 10px;cursor:pointer;margin-right:6px}
 button:hover{border-color:#5d7370}
 #note{color:#8fa3a1}
</style>
<body>
<h1>Champions Ledger &mdash; the three screens at once</h1>
<div id="bar">
  <button onclick="board()">reload all (cache-busted)</button>
  <button onclick="tab('find')">Find</button>
  <button onclick="tab('box')">Box</button>
  <button onclick="tab('builds')">Builds</button>
  <button onclick="tab('teams')">Teams</button>
  <button onclick="tab('gts')">GTS</button>
  <button onclick="tab('damage')">Damage</button>
  <button onclick="sweep()">check for overlaps</button>
  <span id="note"></span>
</div>
<div id="board"></div>
<script>
var SIZES = __SIZES__;
function board(){
  var b = document.getElementById("board");
  b.innerHTML = "";
  SIZES.forEach(function(s){
    var pane = document.createElement("div");
    pane.className = "pane";
    var cap = document.createElement("div");
    cap.className = "cap";
    cap.innerHTML = "<b>" + s[0] + "</b> \\u2014 " + s[1] + "x" + s[2] + " CSS px";
    var f = document.createElement("iframe");
    f.width = s[1]; f.height = s[2];
    /* ALWAYS a fresh URL: a service worker would otherwise hand back the build
       before the one being tested, and the test would prove nothing. */
    f.src = "index.html?t=" + Date.now();
    pane.appendChild(cap); pane.appendChild(f);
    b.appendChild(pane);
  });
  document.getElementById("note").textContent = "";
}
function each(fn){
  return [].map.call(document.querySelectorAll("iframe"), function(f){
    try { return fn(f); } catch (e) { return String(e); }
  });
}
function tab(name){
  each(function(f){ f.contentWindow.go(name); });
  document.getElementById("note").textContent = "  showing: " + name;
}
/* The app's own sweep, run in all three at once - the half of the overlap
   check that knows what a real browser actually did. */
function sweep(){
  var out = each(function(f){
    var D = f.contentDocument;
    var r = f.contentWindow.overlapSweep(D.querySelector(".view:not([hidden])"));
    var over = D.documentElement.scrollWidth - D.documentElement.clientWidth;
    return f.width + ": " + r.hits.length + " overlaps of " + r.boxes +
           " boxes" + (over > 0 ? ", " + over + "px of sideways scroll" : "");
  });
  document.getElementById("note").textContent = "  " + out.join("   |   ");
}
(async function(){
  try {
    var regs = await navigator.serviceWorker.getRegistrations();
    await Promise.all(regs.map(function(r){ return r.unregister(); }));
    var ks = await caches.keys();
    await Promise.all(ks.map(function(k){ return caches.delete(k); }));
  } catch (e) {}
  board();
})();
</script>
"""


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--no-build", action="store_true",
                    help="serve tracker/dist as it stands")
    ap.add_argument("--port", type=int, default=PORT)
    ap.add_argument("--no-open", action="store_true")
    args = ap.parse_args()

    if not args.no_build:
        subprocess.run([sys.executable, str(ROOT / "scripts" / "build_tracker_page.py")],
                       check=True)
    if not (DIST / "index.html").exists():
        sys.exit("tracker/dist has no index.html - run without --no-build")

    import json
    (DIST / "_resolutions.html").write_text(
        PAGE.replace("__SIZES__", json.dumps([[a, b, c] for a, b, c in SIZES])),
        encoding="utf-8")

    url = "http://127.0.0.1:%d/_resolutions.html" % args.port
    print("\n  " + url + "\n")
    if not args.no_open:
        webbrowser.open(url)
    handler = functools.partial(http.server.SimpleHTTPRequestHandler,
                                directory=str(DIST))
    # so a re-run right after Ctrl-C is not refused the port
    socketserver.TCPServer.allow_reuse_address = True
    with socketserver.TCPServer(("127.0.0.1", args.port), handler) as srv:
        try:
            srv.serve_forever()
        except KeyboardInterrupt:
            print("  stopped")


if __name__ == "__main__":
    main()
